/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/providers/CartContext`; params?: Router.UnknownInputParams; } | { pathname: `/screens/CartScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/ProductListingScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/RegisterScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/SplashScreen`; params?: Router.UnknownInputParams; } | { pathname: `/services/CartService`; params?: Router.UnknownInputParams; } | { pathname: `/types/Cart`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/providers/CartContext`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/CartScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/ProductListingScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/RegisterScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/SplashScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/services/CartService`; params?: Router.UnknownOutputParams; } | { pathname: `/types/Cart`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/providers/CartContext${`?${string}` | `#${string}` | ''}` | `/screens/CartScreen${`?${string}` | `#${string}` | ''}` | `/screens/ProductListingScreen${`?${string}` | `#${string}` | ''}` | `/screens/RegisterScreen${`?${string}` | `#${string}` | ''}` | `/screens/SplashScreen${`?${string}` | `#${string}` | ''}` | `/services/CartService${`?${string}` | `#${string}` | ''}` | `/types/Cart${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/providers/CartContext`; params?: Router.UnknownInputParams; } | { pathname: `/screens/CartScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/ProductListingScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/RegisterScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/SplashScreen`; params?: Router.UnknownInputParams; } | { pathname: `/services/CartService`; params?: Router.UnknownInputParams; } | { pathname: `/types/Cart`; params?: Router.UnknownInputParams; };
    }
  }
}
